### ISSUE TITLE
Provide REST API

### ISSUE THREAD

**Issue by FrostyX** [FrostyX/fedora-sponsors#21]
It should be fairly easy to provide API with JSON results for all the information we display on the website:

- https://docs.pagure.org/fedora-sponsors/all
- https://docs.pagure.org/fedora-sponsors/active
- https://docs.pagure.org/fedora-sponsors/interests
- https://docs.pagure.org/fedora-sponsors/languages
- https://docs.pagure.org/fedora-sponsors/regions
- https://docs.pagure.org/fedora-sponsors/timezones

The benefit of this API over FASJSON is that we won't provide any sensitive information and therefore it can work without any authentication. Which is ideal for tools and services - it is annoying to setup [fkinit for services](https://pagure.io/fedora-infrastructure/issue/10239).

Ideally, it should be compatible with the OpenAPI specification, so we can use Swagger.

**Comment by FrostyX** [comment]
A possible customer for this can be a Fedora Review Service in order to check if a `fedora-review+` was given by a sponsor and to fix this issue https://github.com/FrostyX/fedora-review-service/issues/32

**Comment by habibur4340** [comment]
Developing a JSON API for Fedora Sponsors data (e.g., all, active, interests, languages, regions, timezones) without requiring authentication simplifies access for tools and services. Adhering to the OpenAPI specification enhances usability and allows for Swagger integration. [Apidog](https://apidog.com/) can aid in API development, testing, and ensuring OpenAPI compliance, facilitating a seamless developer experience.
