### ISSUE TITLE
Timezones page issues

### ISSUE THREAD

**Issue by oturpe** [FrostyX/fedora-sponsors#3]
The information on _Timezones_ page is already useful, but there are some inaccuracies:

1. The listed large positive utc offsets should be actually listed as negative offsets. For instance, sponsors at US/Eastern should be listed UTC-4 or UTC-5, depending on how you handle daylight saving time. The difference between UTC+20 and UTC-4 is if it is already Monday or still Sunday. Note that there is potential overlap also, because positive zones extend to UTC+14 and negative ones to UTC-12.
2. Minutes should be included, because not all timezones have full hour offset from utc.
3. Unfortunately, daylight saving time is observed in some locations and this makes offsets move back and forth. It seems that currently, the current offset is shown. I think it would be better to show the offset without considering daylight saving, to avoid values changing on certain dates.

**Comment by FrostyX** [comment]
Thank you for the report @oturpe,
I will revisit the timezone generation.

**Comment by FrostyX** [comment]
What do you think now @oturpe?
https://docs.pagure.org/fedora-sponsors/timezones

**Comment by oturpe** [comment]
Thank you, negative offsets and offsets other than full hours work now. Since anything related daylight saving time is tricky and the current display is not more "wrong" than other options, I will close this issue.

**Comment by FrostyX** [comment]
Okay, thank you for the feedback.
