### ISSUE TITLE
Some sponsors' names have FAS prepended

### ISSUE THREAD

**Issue by michel-slm** [FrostyX/fedora-sponsors#4]
See e.g.
https://docs.pagure.org/fedora-sponsors/active
- lbazan: FAS Luis Enrique Bazán De León
- salimma: FAS Michel Alexandre Salim

**Comment by michel-slm** [comment]
Oh, never mind, this must have happened during the FAS migration for those with > 2 words in their full names! I'll let lbazan know

**Comment by FrostyX** [comment]
Thank you for the report.

> Oh, never mind, this must have happened during the FAS migration for those with > 2 words in their full names! 

I think you are correct. In any case, the "FAS" prefix is stored in the accounts system and the sponsors page just prints it. I think you already updated your profile so I tried to rebuild the page and the "FAS" prefix disappeared from your name.

> I'll let lbazan know

Thank you :-)
